version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: studybud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KAnani786.COM
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: studybud
      DB_USER: postgres
      DB_PASSWORD: KAnani786.COM
      DB_HOST: db
      DB_PORT: 5432

      # environment:
      # DB_ENGINE: ${django.db.backends.postgresql}
      # DB_NAME: ${sample}
      # DB_USER: ${postgres}
      # DB_PASSWORD: ${KAnani786.COM}
      # DB_HOST: db
      # DB_PORT: ${5432}